Feat/nexus blobstore
cloud-pi-native/socle pull request #198
Opened 2024-04-09 14:20 UTC by cmon33

## Issues liées

Issues numéro: 

---------

## Quel est le comportement actuel ?

Installe Sonatype Nexus Repository. 

## Quel est le nouveau comportement ?

Installe Sonatype Nexus Repository en lui ajoutant les éléments suivants :
- Le blob store nommé « dso » de taille configurable via la custom resource dsc.
- Un proxy Docker Hub qui utilise le blo bstore dso.
- Une Cleanup Policy nommée « DSOdockerCleanupPolicy ».
- Les tasks associées qui viennent périodiquement compacter le blob store et nettoyer le dépôt proxy Docker Hub.

## Cette PR introduit-elle un breaking change ?

Non.

## Autres informations

La task "Cleanup service" créée par défaut et chargée d'appliquer les cleanup policies aux repositories qui en ont une, ne fait que du soft delete. C'est à dire qu'elle marque les objets pour suppression mais ne les supprime pas réellement. Elle ne libère donc aucun espace côté blo bstore. Pour que l'espace soit véritablement libéré, il faut lui associer certaines tâches.
Ceci est expliqué dans la documentation officielle ici : https://help.sonatype.com/en/cleanup-policies.html
Et plus précisément dans la section suivante : https://help.sonatype.com/en/cleanup-policies.html#hard-deleting-cleaned-up-components
C'est la raison pour laquelle nous avons automatisé la création des tâches recommandées.

La création d'une cleanup policy ou de tasks n'est actuellement pas possible via l'API de Nexus.
Voir à ce sujet les issues suivantes :
- https://github.com/sonatype/nexus-public/issues/149
- https://github.com/sonatype/nexus-public/issues/305

C'est pourquoi, dans l'attente de la résolution de ces issues, nous avons contourné le problème en nous appuyant sur la scripting API proposée par Nexus et sur des scripts groovy permettant de déclarer les éléments souhaités.

2024-04-09 15:06 UTC, ArnaudTA requested changes

2024-04-09 15:06 UTC, ArnaudTA commented on roles/nexus/tasks/main.yaml
> +
on peux mettre le disallow dans un `always:` ?

2024-04-09 15:06 UTC, ArnaudTA commented on roles/nexus/tasks/main.yaml
> +      url: "https://testcm-nexus.apps.c7.numerique-interieur.com/repository/dso-dockerhub-proxy"
popopo c'est quoi cette URL ?

2024-04-09 15:25 UTC, cmon33 commented on roles/nexus/tasks/main.yaml
> +      url: "https://testcm-nexus.apps.c7.numerique-interieur.com/repository/dso-dockerhub-proxy"
Merci.
Corrigé. C'était un relicat dû à l'adaptation de la task à partir de ce que renvoyait l'API dans un cluster de test.

2024-04-09 15:36 UTC, cmon33 commented on roles/nexus/tasks/main.yaml
> +
C'est fait. Merci pour le conseil. ;-)

2024-04-09 15:40 UTC, ArnaudTA approved these changes

2024-04-09 16:38 UTC, mathieulaude commented on roles/nexus/tasks/manage-cleanup-policy.yaml
> +      name: dso-docker-cleanup.json
le contenu est en Groovy donc même si ça ne change pas grand chose, j'aurais mis un nommage des scripts en `.groovy` au lieu de json

2024-04-09 17:03 UTC, mathieulaude requested changes
Règle de purge après 30 jours sans téléchargement à challenger

2024-04-10 08:50 UTC, cmon33 commented on roles/nexus/tasks/manage-cleanup-policy.yaml
> +      name: dso-docker-cleanup.json
Effectivement. Il s'agissait d'un relicat de mes tests, car je me suis initialement appuyé sur des exemples de scripts qui portaient l'extension « .json ».
C'est corrrigé ! :-)

2024-04-10 12:44 UTC, akramWewe approved these changes

2024-04-10 12:44 UTC, akramWewe commented on roles/nexus/tasks/manage-nexus-tasks.yaml
> +            TaskConfiguration taskConfiguration = taskScheduler.createTaskConfigurationInstance("repository.docker.upload-purge")
@cedric-montagne  je pense qu'il fallait rajouter aussi la task "repository.purge-unused" pour cleaner les images dockers non demandées depuis x jours-> Ce task concerne les pull des images non terminés suite à une interruption

2024-04-10 12:44 UTC, akramWewe commented on roles/nexus/tasks/manage-nexus-tasks.yaml
> +            taskConfiguration.setString("age", "24")
@cedric-montagne je pense que c'est beaucoup 24 jours.  Je te proposes de mettre 14 jours pour réduire le risque au niveau de stockage, et on affinera si besoin

2024-04-10 13:16 UTC, cmon33 commented on roles/nexus/tasks/manage-nexus-tasks.yaml
> +            taskConfiguration.setString("age", "24")
Merci pour le retour.
Il s'agit ici de la task qui supprime les uploads Docker incomplets (Docker - Delete Incomplete uploads).
Elle est décrite comme suit :
"Delete incomplete docker uploads that are older than the specified age in hours."
Donc la durée indiquée est en heures et pas en jours.
Je pense donc que nous pouvons la laisser en l'état.

2024-04-10 13:26 UTC, cmon33 commented on roles/nexus/tasks/manage-nexus-tasks.yaml
> +            TaskConfiguration taskConfiguration = taskScheduler.createTaskConfigurationInstance("repository.docker.upload-purge")
Merci pour le retour.
La task "repository.purge-unused" est en fait remplacée par la "Cleanup feature" (repository.cleanup) qui est présente par défaut dans les versions récentes de Nexus et qui s'appuie sur la Cleanup Policy.
Comme expliqué ici : https://help.sonatype.com/en/tasks.html
"Older instances would typically schedule this but this is effectively replaced by the Cleanup feature."
Nous pouvons donc nous passer de la task "repository.purge-unused" qui dans notre cas serait redondante.

2024-04-15 09:20 UTC, cmon33 commented
@mathieulaude 

> Règle de purge après 30 jours sans téléchargement à challenger

Fait ce jour. Les règles de purge sont fonctionnelles.

2024-04-15 09:36 UTC, mathieulaude approved these changes

2024-04-15 09:36 UTC, merged