feat: ✨ combine helm user values
cloud-pi-native/socle pull request #278
Opened 2024-07-23 15:18 UTC by benji78

## Quel est le comportement actuel ?
Seuls ArgoCD, console, GitLab, Harbor, Keycloak, Sonarqube et Vault ont une option pour surcharger les Helm `values` dans `DsoSocleConfig`.

## Quel est le nouveau comportement ?
Ajoute une option `values` dans `DsoSocleConfig` pour CertManager, cloudNativePG, GitLab Operator, GitLab CI Pipeline Exporter, Grafana Operator et Kyverno.

## Cette PR introduit-elle un breaking change ?
Non

## Autres informations
À l'ANFSI, nous travaillons au déploiement de la DSO en airgap et nous avons besoin de surcharger beaucoup de Helm `values`, notamment celles proposés dans cette PR.

2024-07-24 13:16 UTC, cmon33 approved these changes

2024-07-24 13:33 UTC, ArnaudTA requested changes
meme chose qu'en #279
si on peut éviter d'ajouter des lignes `values: {}` dans la CRD mais surcharger par config.
Sinon ça instantie inutilement des lignes dans DSC et complique la lecture.
Le fichier roles/socle-config/files/config.yaml est fait pour justement avoir un fallback

2024-07-24 13:34 UTC, this-is-tobi commented
Ici aussi, s'il est possible de réécrire les messages de commits pour qu'ils suivent [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) ça serait cool (:

*ps: merci pour la participation*

2024-07-24 14:07 UTC, benji78 commented
> Ici aussi, s'il est possible de réécrire les messages de commits pour qu'ils suivent [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) ça serait cool (:

Absolument ! Cependant je trouve ça presque ironique vu certains noms de commits récents :upside_down_face: : `wip`, `init` ou `fix:`

2024-07-24 14:08 UTC, benji78 commented
> meme chose qu'en #279 si on peut éviter d'ajouter des lignes `values: {}` dans la CRD mais surcharger par config. Sinon ça instantie inutilement des lignes dans DSC et complique la lecture. Le fichier roles/socle-config/files/config.yaml est fait pour justement avoir un fallback

Là c'est plus clair. Dans ce cas que faire dans le README ?

2024-07-24 14:22 UTC, ArnaudTA commented
@benji78 Je comprends ce que tu veux dire, on est une toute petite équipe avec bcp de sujets. On essaye d'aller vers le mieux mais des fois il y a des loupés. Le conventional commit a surtout un interet pour avoir des releases notes automatique et ce que tu propose mérite clairement de figurer dedans, et pour ça merci

Pour le Readme je dirais de revert tes changement sur ce fichier vu que ce n'est plus d'actualité.

A vrai dire un lien vers `roles/socle-config/files/cr-conf-dso-default.yaml` aurait largement pu faire l'affaire et éviterait une double maintenance...

2024-07-25 07:46 UTC, benji78 commented
Pourquoi les release notes ne sont-elles pas créés à partir des noms de PR plutôt que des commits (qui pourraient être très nombreux) ?

2024-07-25 10:18 UTC, ArnaudTA commented
Parce que c'est conventionnal *commit* 😉

Sinon j'ai deux trois trucs bêtes qui me chagrine sur ta branche, tu m'autorise à l'éditer ?

2024-07-25 15:20 UTC, benji78 commented
Maintenant oui. D'ailleurs, je n'ai pas pu m'empêcher de corriger toute sorte de typo dans le README.

2024-07-25 22:16 UTC, this-is-tobi commented
> > Ici aussi, s'il est possible de réécrire les messages de commits pour qu'ils suivent [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) ça serait cool (:
> 
> Absolument ! Cependant je trouve ça presque ironique vu certains noms de commits récents 🙃 : `wip`, `init` ou `fix:`

Ahah ! C'est justement parce que certains sont passés à la trape que je voudrais éviter que ça se reproduise (je vais les réécrire avant la prochaine release je pense).

Merci à toi en tout cas @benji78 ! Si tu as des interrogations sur le fonctionnement de certaines choses, etc n'hésites surtout pas à nous en faire part, comme disait Arnaud, on est une toute petite équipe et on fait ce qu'on peut (on a d'autres dépôts à maintenir en plus de plusieurs plateformes). On répondra / échangera avec toi en direct au besoin (webconf) selon nos dispos respectives (:

2024-08-03 12:40 UTC, benji78 commented
J'ai fait un rebase de ma branche, mais je n'ai pas compris pourquoi tout l'historique de la branche develop à été supprimé et remplacé par les noms des pull requests.

2024-08-05 22:23 UTC, this-is-tobi commented
> J'ai fait un rebase de ma branche, mais je n'ai pas compris pourquoi tout l'historique de la branche develop à été supprimé et remplacé par les noms des pull requests.

Ah étonnant tiens, pas si grave je ferai une repasse sur l'historique avant de faire la prochaine release au besoin !

Je vais t'embêter mais avec le bal des merge il faudrait re-rebase, merci pour les participations en tout cas !

@ArnaudTA tu voulais ajouter / réécrire des choses ?

2024-08-06 21:47 UTC, benji78 commented on roles/socle-config/files/cr-conf-dso-default.yaml
> +    metrics: {}
Pour `metrics` et `alerting` j'ai retiré `enabled: false` qui est la valeur par défaut dans le CRD et dans `config.yaml`. Mais peut-être faut-il, comme pour les values, retirer le `default` du CRD ?

Par ailleurs, pour organiser une reunion webconf par quel moyen peut on vous contacter ?

2024-08-09 14:05 UTC, this-is-tobi commented
Hello @benji78, désolé pour le temps de réponse, tu pourrais me donner ton adresse mail pro ? Histoire que je puisse t'inviter sur notre Mattermost pour échanger plus facilement et convenir d'un point qu'on pourrait faire ensemble ?

2024-09-23 13:59 UTC, ArnaudTA approved these changes

2024-09-23 13:59 UTC, this-is-tobi approved these changes

2024-09-23 13:59 UTC, merged