feat: ✨ add helm repo url
cloud-pi-native/socle pull request #279
Opened 2024-07-24 12:36 UTC by benji78

## Quel est le comportement actuel ?
Les url des repository helm ne sont pas modifiables, donc la DSO ne peut pas être installé en airgap.

## Quel est le nouveau comportement ?
`helmRepoUrl` peut être utilisé pour surcharger la valeur par défaut du chart repository, déplacé dans le CRD, de `argocd`, `certmanager`, `cloudnativepg`, `console`, `gitlabOperator`, `gitlabCiPipelinesExporter`, `gitlabRunner`, `harbor`, `keycloak`, `kyverno`, `sonarqube` et `vault`. 
`dsc.grafanaOperator.ociChartUrl` est également utilisé pour surcharger la valeur par défaut, mais il s'agit d'un registre Helm basé sur OCI.

## Cette PR introduit-elle un breaking change ?
Pour rendre uniform et retirer la répétition de "console", `consoleRepoUrl` à été changé en `helmRepoUrl`.

De la même façon, `dsc.catalog.catalogRepoUrl` **devrait**, à mon avis, être changé en `repoCloneUrl` pour éviter la répétition et rendre plus claire le fait qu'il s'agit de l'url http pour cloner le dépôt de GitLab Catalog.

## Autres informations
À l'ANFSI, nous travaillons au déploiement de la DSO en air gap et nous avons besoin de surcharger l'url des dépôts Helm (et registre OCI pour Grafana operator).
Je n'ai pas souhaité ajouter dans le nouveau role `cluster-offline` la verification que ces valeurs soient définies en dehors de `dsc.console.helmRepoUrl`.

2024-07-24 13:05 UTC, cmon33 approved these changes

2024-07-24 13:12 UTC, this-is-tobi approved these changes

2024-07-24 13:25 UTC, ArnaudTA requested changes
Il faudrait déplacer les default de la dsc dans roles/socle-config/files/config.yaml
La dsc doit pouvoir fonctionner sans value. et le code doit compléter. pas avec un default que le code ne saura pas si il override si on doit changer à l'avenir

2024-07-24 13:33 UTC, this-is-tobi commented
J'en profite, je n'avais pas fait attention, s'il est possible de réécrire les messages de commits pour qu'ils suivent [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) ça serait cool (:

*ps: merci pour la participation*

2024-07-25 10:08 UTC, ArnaudTA approved these changes

2024-07-25 10:08 UTC, ArnaudTA commented on roles/grafana-operator/tasks/main.yaml
> +        chart_ref: "oci://{{ dsc.grafanaOperator.ociChartUrl }}"
Une raison pour ne pas avoir mis le protocol dans la variable ?

2024-07-25 12:45 UTC, benji78 commented on roles/grafana-operator/tasks/main.yaml
> +        chart_ref: "oci://{{ dsc.grafanaOperator.ociChartUrl }}"
J'avais initialement mis `dsc.global.repository` à la place de `ghcr.io`, puis en le mettant de cette façon, il me semblait qu'un [registre Helm basé sur OCI](https://helm.sh/docs/topics/registries/) était la seul possibilité.
Je devrais donc renommer la variable en `helmChartUrl`, mais c'est un peu trop proche de `helmRepoUrl` à mon goût.

2024-07-25 14:10 UTC, ArnaudTA commented on roles/grafana-operator/tasks/main.yaml
> +        chart_ref: "oci://{{ dsc.grafanaOperator.ociChartUrl }}"
je veux dire que que la variable `dsc.grafanaOperator.ociChartUrl` peut contenir `oci://` comme pour le `https://` dans toutes les autres vars

2024-07-25 14:11 UTC, ArnaudTA commented on roles/socle-config/files/config.yaml
> +    ociChartUrl: ghcr.io/grafana/helm-charts/grafana-operator
oci://ghcr.io/grafana/helm-charts/grafana-operator
concernant mon précédent commentaire

2024-07-25 15:54 UTC, benji78 commented on roles/grafana-operator/tasks/main.yaml
> +        chart_ref: "oci://{{ dsc.grafanaOperator.ociChartUrl }}"
Oui, j'ai bien compris. Mais c'est maintenant le nom de la variable qui me chagrine puisque `ociChartUrl` pourrait également contenir autre chose qu'une url en `oci://` (i.e. `https://`)  comme indiqué dans [`kubernetes.core.helm.char_ref`](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html#parameter-chart_ref).

2024-07-25 16:02 UTC, benji78 commented on roles/grafana-operator/tasks/main.yaml
> +        chart_ref: "oci://{{ dsc.grafanaOperator.ociChartUrl }}"
Maintenant si vous pensez que ce n'est pas important, la PR est prête.

2024-07-25 22:09 UTC, this-is-tobi approved these changes

2024-07-26 08:09 UTC, ArnaudTA approved these changes

2024-07-26 09:52 UTC, benji78 commented
Je viens de remarquer une erreur dans #221.
consoleRepoUrl: `https://cloud-pi-native.github.io/helm-charts`
est comparé à `https://github.com/cloud-pi-native/console.git` (mauvaise url)
ici https://github.com/Falltrades/socle/blame/87e6bd6c1a79cbbeb9113919f7cb73c16736fb0d/roles/cluster-offline/tasks/main.yml#L23-L24

Du coup autant retirer la comparaison qui est inutile. Sinon, il faudrait ajouter une validation pour tous les `helmRepoUrl` ajoutés ici.

2024-07-29 07:56 UTC, merged