fix: :bug: Fix Argo CD role
cloud-pi-native/socle pull request #326
Opened 2024-08-28 16:02 UTC by cmon33

To permit dual installation without impacting cluster roles

## Issues liées

Issues numéro: 

---------

## Quel est le comportement actuel ?

Installe Argo CD en laissant le chart Helm gérer les ClusterRoles.
Ceci ne permet pas une "dual install" propre d'Argo CD dans le même cluster, car il faut pouvoir renommer les ClusterRoles et CRBs associés, ce que ne permettent pas actuellement les values du chart.

## Quel est le nouveau comportement ?

Une "dual install" d'Argo CD dans un même cluster est maintenant fonctionnelle.

## Cette PR introduit-elle un breaking change ?

Non.

## Autres informations

Comportement testé et validé dans un cluster de développement.

2024-08-29 16:02 UTC, ArnaudTA requested changes
Le script d'uninstall devrait prévoir de ne pas laisser ces fichiers aussi

2024-08-29 16:02 UTC, ArnaudTA commented on roles/argocd/templates/argo-argocd-application-controller-cr.yaml.j2
> +    app.kubernetes.io/part-of: argocd
ce sont des labels spécifiques à un déploiement helm ça, si tu veux uninstall je me demande comment ça réagit

2024-08-30 09:38 UTC, cmon33 commented on roles/argocd/templates/argo-argocd-application-controller-cr.yaml.j2
> +    app.kubernetes.io/part-of: argocd
C'est corrigé via un refactor complet qui, comme vu ensemble, nous permet également de mieux gérer la désinstallation.

2024-08-30 09:56 UTC, ArnaudTA approved these changes

2024-08-30 09:57 UTC, merged