Fix/cnpg backups and argocd proxy
cloud-pi-native/socle pull request #358
Opened 2024-10-11 17:56 UTC by this-is-tobi

## Quel est le comportement actuel ?

- L'installation du composant Argo-cd avec un proxy est défeuctueuse.
- Les backups des clusters CNPG doivent être désactivé durant la phase de restauration de la DB.

## Quel est le nouveau comportement ?

- Le `no_proxy` est désormais correctement paramétré.
- Les backups CNPG sont désactivés avec le mode `restore`.

## Cette PR introduit-elle un breaking change ?

Non.

## Autres informations

2024-10-11 18:53 UTC, Falltrades requested changes

2024-10-11 18:53 UTC, Falltrades commented on roles/argocd/templates/values/10-proxy.j2
> +      value: "{{ dsc.proxy.no_proxy }},"{{ dsc_name }}-argocd-repo-server"
```suggestion
      value: "{{ dsc.proxy.no_proxy }},{{ dsc_name }}-argocd-repo-server"
```

2024-10-14 07:14 UTC, cmon33 approved these changes

2024-10-14 07:56 UTC, Falltrades approved these changes

2024-10-14 08:02 UTC, merged